cath:
  coindesk:
    url: https://api.coindesk.com/v1/bpi/currentprice.json
  bpi:
    tw:
     USD: 美元
     GBP: 英鎊
     EUR: 歐元

#spring:
#   gson:
#    date-format: yyyy-MM-dd hh:mm

spring:
  datasource:
    url: jdbc:h2:mem:testdb #h2 DB連接位址
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jdbc:
    template:
      query-timeout: 90
  jpa:
    hibernate:
      # 更新或創建table
      ddl-auto: none
      # console顯示SQL
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2-console   #h2 web控制台路徑
      enabled: true       #開啟web console
      settings:
        web-allow-others: true    #允許遠端訪問web console